# Generated by Django 3.0.2 on 2020-02-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(upload_to='uploaded/')),
                ('uploadedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadsongs', to='Registration.Registration')),
            ],
            options={
                'db_table': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='MusicMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='music_description')),
                ('title', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('song', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs_data', to='BeatXMusic.Song')),
            ],
            options={
                'db_table': 'Musicdata',
            },
        ),
    ]
