# Generated by Django 3.0.2 on 2020-02-04 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to say', 'Hidden')], max_length=20, verbose_name='gender')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('email_addr', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('password', models.CharField(db_tablespace='pass', max_length=200, verbose_name='password')),
                ('profile_pic', models.ImageField(blank=True, upload_to='uploaded')),
            ],
            options={
                'db_table': 'Registration',
            },
            managers=[
                ('register', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='Registration.Registration')),
                ('self_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='Registration.Registration')),
            ],
            options={
                'db_table': 'user_friends',
            },
        ),
    ]
